// src/components/HeroSection.tsx
import { motion } from 'framer-motion'
import { Button } from './ui/button'
import { ArrowRight, Sparkles } from 'lucide-react'
import { ImageWithFallback } from './figma/ImageWithFallback'

export function HeroSection() {
  return (
    <section
      id='hero'
      className='relative min-h-screen flex items-center justify-center overflow-hidden bg-black'>
      <div className='absolute inset-0 bg-black'>
        <div className='absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(240,184,93,0.15),transparent_50%),radial-gradient(circle_at_70%_80%,rgba(217,158,74,0.1),transparent_50%)]' />

        <div
          className='absolute inset-0 opacity-[0.03]'
          style={{
            backgroundImage: `repeating-linear-gradient(
              45deg,
              #f0b85d,
              #f0b85d 2px,
              transparent 2px,
              transparent 60px
            )`,
          }}
        />

        <div
          className='absolute inset-0 opacity-[0.08]'
          style={{
            backgroundImage:
              'radial-gradient(circle, #f0b85d 1px, transparent 1px)',
            backgroundSize: '40px 40px',
          }}
        />

        <motion.div
          className='absolute top-1/4 right-1/4 w-[500px] h-[500px] rounded-full opacity-10 blur-[100px]'
          style={{
            background: 'radial-gradient(circle, #f0b85d, transparent 70%)',
          }}
          animate={{
            scale: [1, 1.3, 1],
            x: [0, 30, 0],
            y: [0, -20, 0],
          }}
          transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
        />
        <motion.div
          className='absolute bottom-1/3 left-1/3 w-[400px] h-[400px] rounded-full opacity-8 blur-[100px]'
          style={{
            background: 'radial-gradient(circle, #d99e4a, transparent 70%)',
          }}
          animate={{
            scale: [1.2, 1, 1.2],
            x: [0, -30, 0],
            y: [0, 20, 0],
          }}
          transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
        />

        <div className='absolute top-10 right-10 w-32 h-32 opacity-5'>
          <svg viewBox='0 0 100 100' className='w-full h-full'>
            <polygon
              points='50 1 95 25 95 75 50 99 5 75 5 25'
              fill='none'
              stroke='#f0b85d'
              strokeWidth='2'
            />
          </svg>
        </div>
      </div>

      <div className='container mx-auto px-4 py-20 relative z-10'>
        <div className='grid md:grid-cols-2 gap-12 items-center'>
          <div className='space-y-8'>
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className='inline-flex items-center gap-2 bg-[#f0b85d]/10 border border-[#f0b85d]/30 rounded-full px-4 py-2'>
              <Sparkles className='w-4 h-4 text-[#f0b85d]' />
              <span className='text-[#f0b85d]'>
                Gestão Inteligente para Salões
              </span>
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className='text-white text-5xl md:text-6xl lg:text-7xl'>
              Transforme seu negócio com{' '}
              <span className='bg-gradient-to-r from-[#f0b85d] to-[#d4a046] bg-clip-text text-transparent'>
                gestão inteligente
              </span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              className='text-[#e5e5e5] text-xl'>
              SalonSync é a solução completa para modernizar a gestão do seu
              salão de beleza ou barbearia.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.6 }}
              className='flex flex-col sm:flex-row gap-4'>
              <motion.div
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}>
                <Button className='bg-gradient-to-r from-[#f0b85d] to-[#d4a046] text-black hover:shadow-[0_0_30px_rgba(240,184,93,0.5)] transition-all px-8 py-6 group cursor-pointer'>
                  Começar Agora
                  <ArrowRight className='ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform' />
                </Button>
              </motion.div>
            </motion.div>
          </div>

          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 1, delay: 0.4 }}
            className='relative flex justify-center items-center'>
            <motion.div
              animate={{ y: [0, -15, 0] }}
              transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
              className='relative z-10 w-full max-w-2xl'>
              <div className='rounded-xl overflow-hidden shadow-[0_20px_60px_rgba(240,184,93,0.3)] border border-[#f0b85d]/20 bg-black/40 backdrop-blur-sm p-3'>
                <div className='aspect-video rounded-lg overflow-hidden'>
                  <ImageWithFallback
                    src='https://images.unsplash.com/photo-1758411898049-4de9588be514?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBkYXNoYm9hcmQlMjBpbnRlcmZhY2V8ZW58MXx8fHwxNzYwNTIyNzg3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral'
                    alt='SalonSync Dashboard'
                    className='w-full h-full object-cover'
                  />
                </div>
              </div>
            </motion.div>

            <motion.div
              animate={{ y: [0, 10, 0], rotate: [0, 5, 0] }}
              transition={{ duration: 3, repeat: Infinity, ease: 'easeInOut' }}
              className='absolute -top-6 -right-6 w-24 h-24 bg-[#f0b85d] opacity-20 blur-3xl rounded-full'
            />
            <motion.div
              animate={{ y: [0, -10, 0], rotate: [0, -5, 0] }}
              transition={{
                duration: 3.5,
                repeat: Infinity,
                ease: 'easeInOut',
              }}
              className='absolute -bottom-6 -left-6 w-24 h-24 bg-[#f0b85d] opacity-20 blur-3xl rounded-full'
            />
          </motion.div>
        </div>
      </div>
    </section>
  )
}

// src/components/HeroSection.vue
<script setup>
import { whatsappLink } from "../data/contactData.js";
</script>

<template>
  <section
    id="home"
    class="hero-gradient pt-20 pb-16 min-h-screen flex items-center"
  >
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
      <div class="grid lg:grid-cols-2 gap-12 items-center h-full">
        <div class="fade-in flex flex-col justify-center h-full">
          <h1
            class="text-4xl sm:text-5xl lg:text-6xl font-bold mb-6 leading-tight"
            style="color: var(--black-soft)"
          >
            Transforme seu salão com
            <span style="color: var(--yellow-strong)">gestão inteligente</span>
          </h1>
          <p
            class="text-lg sm:text-xl mb-8 leading-relaxed"
            style="color: var(--gray-dark)"
          >
            SalonSync é a solução completa para modernizar a gestão do seu salão
            de beleza ou barbearia. Agende, controle e cresça com tecnologia de
            ponta.
          </p>
          <div class="flex flex-col sm:flex-row gap-4">
            <a
              :href="whatsappLink"
              target="_blank"
              rel="noopener noreferrer"
              class="btn-primary px-8 py-4 rounded-full text-lg font-semibold inline-flex items-center justify-center"
            >
              <i class="fas fa-rocket mr-2"></i>Começar Agora
            </a>
            <button
              class="border-2 px-8 py-4 rounded-full text-lg font-semibold hover:bg-gray-50 transition-all duration-300"
              style="
                border-color: var(--yellow-strong);
                color: var(--yellow-strong);
              "
            >
              <i class="fas fa-play mr-2"></i>Ver Demo
            </button>
          </div>
        </div>

        <div class="fade-in flex items-center justify-center h-full">
          <div class="relative w-full max-w-2xl">
            <div
              class="bg-black rounded-2xl shadow-2xl overflow-hidden transform rotate-3 hover:rotate-0 transition-transform duration-500"
            >
              <video
                src="/demo.mp4"
                autoplay
                muted
                loop
                playsinline
                class="w-full h-auto object-cover"
                style="min-height: 400px;"
              ></video>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.hero-gradient {
  background: linear-gradient(135deg, var(--off-white) 0%, var(--beige-light) 100%);
}

.btn-primary {
  background-color: var(--yellow-strong);
  color: white;
  transition: all 0.3s ease;
}

.btn-primary:hover {
  background-color: var(--brown-dark);
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(203, 161, 31, 0.3);
}

.fade-in {
  opacity: 0;
  transform: translateY(30px);
  animation: fadeInUp 0.8s ease forwards;
}

@keyframes fadeInUp {
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@media (max-width: 1023px) {
  .hero-gradient {
    padding-top: 6rem;
    padding-bottom: 6rem;
    min-height: auto;
  }
  
  video {
    min-height: 300px;
    margin-top: 2rem;
  }
}
</style>
